services:
  nginx:
    container_name: ${CONTAINER_NAME}
    restart: on-failure
    build: ./requirements/nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./requirements/nginx/conf/my_domain/:/var/www/my_domain/