services:
  nginx:
    container_name: ${CONTAINER_NAME_NGINX}
    restart: on-failure
    build: ./requirements/nginx
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress

  db:
    container_name: ${CONTAINER_NAME_MARIADB}
    restart: on-failure
    build: ./requirements/mariadb
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    container_name: ${CONTAINER_NAME_WORDPRESS}
    restart: on-failure
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - db
    networks:
      - inception
    env_file:
      - .env

volumes:
  wordpress_data:
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress/
      o: bind
  db_data:
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb/
      o: bind

networks:
  inception: