services:
  nginx:
    container_name: ${CONTAINER_NAME_NGINX}
    restart: on-failure
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf/my_domain/:/var/www/my_domain/

networks:
  inception: