services:
  nginx:
    container_name: ${CONTAINER_NAME_NGINX}
    restart: always
    build: ./requirements/nginx
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/wordpress

  wordpress:
    container_name: ${CONTAINER_NAME_WORDPRESS}
    restart: always
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - db
    networks:
      - inception
    env_file:
      - .env
  
  db:
    container_name: ${CONTAINER_NAME_MARIADB}
    restart: always
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress/
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb/
      o: bind

networks:
  inception: