services:
  nginx:
    container_name: ${CONTAINER_NAME_NGINX}
    restart: on-failure
    build: ./requirements/nginx
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - /home/${USER}/data/wordpress/:/var/www/wordpress

  wordpress:
    container_name: ${CONTAINER_NAME_WORDPRESS}
    restart: on-failure
    build: ./requirements/wordpress
    volumes:
      - /home/${USER}/data/wordpress/:/var/www/wordpress
    depends_on:
      - db
    networks:
      - inception
    env_file:
      - .env

  db:
    container_name: ${CONTAINER_NAME_MARIADB}
    restart: on-failure
    build: ./requirements/mariadb
    volumes:
      - /home/${USER}/data/mariadb/:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

networks:
  inception: